### ISSUE TITLE
Not working on Python 3.6 - "set_wakeup_fd only works in main thread"

### ISSUE THREAD

**Issue by Tetracerus** [famzah/ping-multi-ext#5]
$ cat /etc/redhat-release 
Rocky Linux release 8.10 (Green Obsidian)

$ pip3 install --user ping-multi-ext
```
Requirement already satisfied: ping-multi-ext in /home/USER/.local/lib/python3.6/site-packages
Requirement already satisfied: blessings in /home/USER/.local/lib/python3.6/site-packages (from ping-multi-ext)
Requirement already satisfied: curtsies in /home/USER/.local/lib/python3.6/site-packages (from ping-multi-ext)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from blessings->ping-multi-ext)
Requirement already satisfied: cwcwidth in /home/USER/.local/lib/python3.6/site-packages (from curtsies->ping-multi-ext)
Requirement already satisfied: backports.cached-property in /home/USER/.local/lib/python3.6/site-packages (from curtsies->ping-multi-ext)
Requirement already satisfied: typing>=3.6; python_version < "3.7" in /home/USER/.local/lib/python3.6/site-packages (from backports.cached-property->curtsies->ping-multi-ext)
```

$ ~/.local/bin/ping-multi 127.0.0.1
```
Exception in thread stdin_processor:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 937, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 885, in run
    self._target(*self._args, **self._kwargs)
  File "/home/USER/.local/lib/python3.6/site-packages/ping_multi_ext/core.py", line 540, in thread_runner
    func(*args[1:])
  File "/home/USER/.local/lib/python3.6/site-packages/ping_multi_ext/core.py", line 554, in stdin_processor
    with curtsies.Input() as input_generator:
  File "/home/USER/.local/lib/python3.6/site-packages/curtsies/input.py", line 116, in __enter__
    signal.set_wakeup_fd(wfd)
ValueError: set_wakeup_fd only works in main thread
```

**Comment by famzah** [comment]
Hello,

Please provide the ``version of Python``, as well as the versions of the ``Python modules``:
```
blessings
curtsies
six
cwcwidth
backports.cached-property
typing>=3.6
```

**Comment by famzah** [comment]
@Tetracerus, please provide the debug info, so that I can reproduce and fix the issue.

**Comment by Tetracerus** [comment]
Package        Version
-------------- -------
Python 3.6.8
backports.cached-property (1.0.2)
blessings (1.7)
curtsies (0.3.10)
cwcwidth (0.1.5)
six (1.11.0)
typing (3.7.4.3)

**Comment by famzah** [comment]
This seems to be a bug in Python 3.6 [which is EOL](https://devguide.python.org/versions/) for almost 3 years now. I tried this on RHEL 8 with Python 3.8 and there are no problems:
```bash
[root@ip-10-0-0-53 ec2-user]# yum install python38
[ec2-user@ip-10-0-0-53 ~]$ pip3.8 install --user ping-multi-ext
[ec2-user@ip-10-0-0-53 ~]$ python3.8 ~/.local/bin/ping-multi 127.0.0.1
```

Please upgrade to a more recent version of Python.
